name: SleepInducer
options:
  bundleIdPrefix: com.sleepinducer
  deploymentTarget:
    iOS: "26.2"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.2"
    IPHONEOS_DEPLOYMENT_TARGET: "26.2"

targets:
  SleepInducer:
    type: application
    platform: iOS
    sources:
      - path: SleepInducer
        excludes:
          - "*.entitlements"
      - path: Shared
        buildPhase: sources
    scheme:
      testTargets: []
      gatherCoverageData: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sleepinducer.app
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: SleepInducer/SleepInducer.entitlements
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "Sleep Inducer uses your health data to show you how app blocking improves your sleep quality."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "Sleep Inducer can log sleep data to help you track your progress."
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - target: SleepInducerMonitor
      - framework: FamilyControls.framework
        embed: false
      - framework: DeviceActivity.framework
        embed: false
      - framework: ManagedSettings.framework
        embed: false
      - framework: HealthKit.framework
        embed: false

  SleepInducerMonitor:
    type: app-extension
    platform: iOS
    sources:
      - path: SleepInducerMonitor
        excludes:
          - "*.entitlements"
      - path: Shared
        buildPhase: sources
    scheme:
      testTargets: []
      gatherCoverageData: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sleepinducer.app.monitor
        INFOPLIST_FILE: SleepInducerMonitor/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: SleepInducerMonitor/SleepInducerMonitor.entitlements
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SKIP_INSTALL: YES
    dependencies:
      - framework: FamilyControls.framework
        embed: false
      - framework: DeviceActivity.framework
        embed: false
      - framework: ManagedSettings.framework
        embed: false
